/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-hover': 'rgb(var(--primary-hover) / <alpha-value>)',
        'primary-active': 'rgb(var(--primary-active) / <alpha-value>)',
        'primary-text': 'rgb(var(--primary-text) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        fg: 'rgb(var(--fg) / <alpha-value>)',
        'fg-muted': 'rgb(var(--fg-muted) / <alpha-value>)',
        'fg-subtle': 'rgb(var(--fg-subtle) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-2': 'rgb(var(--border-2) / <alpha-value>)',
        'border-3': 'rgb(var(--border-3) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        success: 'rgb(var(--success) / <alpha-value>)',
        destructive: 'rgb(var(--destructive) / <alpha-value>)',
        'destructive-hover': 'rgb(var(--destructive-hover) / <alpha-value>)',
        'destructive-active': 'rgb(var(--destructive-active) / <alpha-value>)',
      },
      fontFamily: {
        display: ["JetBrains Mono", "'Fira Code'", "'Cascadia Code'", 'monospace'],
        body: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Helvetica', 'sans-serif'],
        mono: ["JetBrains Mono", "'Fira Code'", 'Consolas', 'monospace'],
      },
      fontSize: {
        display: ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        headline: ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        subhead: ['20px', { lineHeight: '1.4' }],
        bodylg: ['18px', { lineHeight: '1.7' }],
        body: ['16px', { lineHeight: '1.7' }],
        small: ['14px', { lineHeight: '1.6' }],
        caption: ['12px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        overline: ['11px', { lineHeight: '1.4', letterSpacing: '0.1em' }],
        code: ['14px', { lineHeight: '1.65' }],
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
